language: java
jdk: openjdk11
os: linux
dist: focal
env:
  matrix:
  - GITHUB_EMAIL=jonathan.i.percival@gmail.com
  - GITHUB_USER=JPercival
  global:
  - secure: Y1YsNKrg6JmygdLMpTHaHY+3NcID8jd9yiSF0S+ccRQsyOF1AfmrlEvJn6bbKpSmDE/AODKLhrCWgaE2wqgMmDhIxNGS7yMg4VhEMGnqc+7AuMMilDzt38DCTrTavdOOAx7qbQxfWpvlVJPaCA7yqHgeUzU1wS2s/RJqQYBRr1Cqicv+LJgmF0310aCkRZoEgJLh0yiwAzOX0hXi6ugjxiUoPw9muiIoCBtzNt57Qk3QaPT1rl2fIaJ6P6PMJdkhWASt0mawnY3GMtGSa424O+Q2qaMP2dRwJYMPbIKH82x2roBRqJClPQONdSCzjzoWg7ozkauhVFCSa1WjWTsjKj51bBnT9QNZNtBy0opzGRizcU+g1HBPbtqCM5BC30tVyxZ5H5zmVibq+H0zpy7Koyg/vPnjwC4y4zSuNP5TCKtD2IDP+2mY6kIb31SlhuPHO1p++hbo0++zzc0U2B0eP0ASDbhrXqc227che3x50PDD0tJCqEk5ceivHcSPCiMB+YFSZva4Me2wKmusScKndkpRsF7aRuqRuJ8DhZ7MK6MVYjqpsWBY6Yalh10v3fduTaRgI1+2qgmUk8ZvdoNVw5lKXOY6IxHa6l3gi2UkwMpILPANSlLkEHYPACaE38wY6I1yFYNu2lqpcqBtXzFLOP/bai9fYFRVnFZYD3V8nUc=
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
before_install:
- sudo apt-get -y install hub
script:
- "./scripts/build.sh"
notifications:
  slack:
  - rooms: 
    secure: HN1dTe8fkulHNTRU7WcGnZQKQU21WNr55QZFogdM5wMSaogfFVemeL1qON0OU/wSJgUHEbfyI3CPi4GbCu9GNxMn1m/rM/RztnOi5VM30gAn9yH0ST8pJpwgAX9FTDK07xkPCbJFRQk3iWH/+U+iAmmSma5RRb28QsqHCETYD1S1hm/ko3BJwold/pcwnIxgI0NEb3Jk0lO2Rm2HAvXrPcfUXhfB/hkNPCe+SmvY7S0+OWUbki8noS5AqL/HQ6tztsRZFz7tvnBVI5Gc0VlZoIY2FeDeZBDilfZvuEaRnAcsjPzYKnMn631xd1G8j26mgnxSGctzATThfdYV1yJrPQLI3F8oJpl9Mg/nZ0d0+SgSMfU4IB8Utontm6Wa5gypQ8dDeEJrk7yBQVvigupUxpcpx90yBAhb4bEnEhETh9R2i1ghzI3ruGx7x8uEhe84YW9qDe62hNZPzXJox1S5VI8RdHmDwUJvAOMxmMBkC6L2SySAv+oFn+XzJ1xKUecJd2B5I991V7jJvimnXjOkWyJ1k/mp5taZPChUYjoT5rmgSEIPolnzzvyQg2gemvqCr/JZAIAaeStyfDt7YYbFAcqzURXdW+JEAao8c9d5yQvfen7nrCCbNuL3bNo7zUCPZSGaXd6MJyDIkne1iZNbknoxhF9+nENGBOwnuX7p95Q=
    on_success: always
    on_failure: never
  - rooms: 
    secure: IZMERnhhoMqPBN7zv6JX/sp1UA8iUQiQl4BMdnY1c6jDC+J1C4lN8EHnLwyBq7PlGeDNtm9mNouXew4nwM2mrMC3Ch6j9IHqlZHkQklYAKEEpJJnrNKoSTIxmLUpc4WKEA3xC4lxy+vDJGb6uFiNjBLgf3rXeTcUN97MGpJECNOlNbb+mH6HgsGipeSN35pHmv28baPsA7wDzG2/qPHOGBPrnrd4ecJ/ZJvx/LfhiM6UJvWT/LOy7dyZlQzDB6ma4Uwdf9DYZaD0dFY8Of9Oea+mDtKDxX0gKDiCccIDspe9isD8cKh6kpE7/zNPrPHGHqYZem3rVmgkkr7icmi3mKIuJ71r7++/4kBRQWMvlowZRcrvfJ6gLtDNLL30iRthr531pp6o0USxGU/2nWUgzdpD9nm5kmoE/o7uJ/cIjEA118T0jVf6lfdvy0l4XnXOcmGlQLhIpU5AaGZ5NzRm22j5BV9OJfw2g0PqWxvB11DSlX+VxYb/srA2mfzvJDlSg8qgD32176Pc/9PqCJ6a20V1lgWerYGdnhAl109+dTK83lHC36PcsvDHY34V6ZEWim37N7qiDtJYaiG95mgf5Aw3ri72DI2tgDB3NMw/PpSAyVjF6r6M/tWFqzToynawjd7QvJvU+8i5+b0Fp60HmNZBHptSmXQ6+YQH9030Gu4=
    on_success: never
    on_failure: always
